name: image_to_svg
description: "A Rust FFI plugin to convert image to SVG."
version: 0.0.2
repository: https://github.com/lp7799/image_to_svg
topics:
  - ffi
  - svg
  - image
  - rust
  - flutter-plugin



environment:
  sdk: '>=3.3.0 <4.0.0'      
  flutter: '>=3.19.0'         

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.11.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
