// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> convertPixelsToSvgFile({
  required List<int> imageBytes,
  required String outputPath,
  FlutterConversionOptions? options,
}) => RustLib.instance.api.crateApiImageToSvgConvertPixelsToSvgFile(
  imageBytes: imageBytes,
  outputPath: outputPath,
  options: options,
);

class FlutterConversionOptions {
  final int scale;
  final int alphaThreshold;
  final bool crispEdges;
  final bool autoResize;

  const FlutterConversionOptions({
    required this.scale,
    required this.alphaThreshold,
    required this.crispEdges,
    required this.autoResize,
  });

  static Future<FlutterConversionOptions> default_() =>
      RustLib.instance.api.crateApiImageToSvgFlutterConversionOptionsDefault();

  @override
  int get hashCode =>
      scale.hashCode ^
      alphaThreshold.hashCode ^
      crispEdges.hashCode ^
      autoResize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterConversionOptions &&
          runtimeType == other.runtimeType &&
          scale == other.scale &&
          alphaThreshold == other.alphaThreshold &&
          crispEdges == other.crispEdges &&
          autoResize == other.autoResize;
}
